name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  publish:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install 'build' and 'wheel'
        run: pip install build wheel

      - name: Build source tarball and binary
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
